const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

const AUTH_LOGOUT = "AUTH_LOGOUT";

export {AUTH_LOGIN_REQUEST, AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAIL,
        AUTH_REGISTER_REQUEST, AUTH_REGISTER_SUCCESS, AUTH_REGISTER_FAIL,
        AUTH_LOGOUT};