const VOUCHER_REQUEST = "VOUCHER_REQUEST";
const VOUCHER_SUCCESS = "VOUCHER_SUCCESS";
const VOUCHER_FAIL = "VOUCHER_FAIL";

const VOUCHER_DATA_REQUEST = "VOUCHER_DATA_REQUEST";
const VOUCHER_DATA_SUCCESS = "VOUCHER_DATA_SUCCESS";
const VOUCHER_DATA_FAIL = "VOUCHER_DATA_FAIL";

export {VOUCHER_REQUEST, VOUCHER_SUCCESS, VOUCHER_FAIL, VOUCHER_DATA_REQUEST, VOUCHER_DATA_SUCCESS, VOUCHER_DATA_FAIL}
